[package]
name = "countdown-numbers-game"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
rand = "0.9.2"


[[bench]]
name = "bruteforce_bench"
harness = false

[[bench]]
name = "minimax_bench"
harness = false
